### ISSUE TITLE
RTL Leads to system crash on windows

### ISSUE THREAD

**Issue by sendbitcoin** [Ride-The-Lightning/RTL#1003]
When i start RTL my windows 10 PC crashes and restarts after a couple minutes

you don't have to do anything and it happens pretty quickly

I updated to the newest version of RTL but the problem is still happening. never had this problem with older versions

![image](https://user-images.githubusercontent.com/60074674/165186552-bac90183-34e1-48ad-98a4-3a1d60b2b670.png)

I was having lots of problem with system stability so i stopped RTL and left lnd running and it ran for 27 days, never crashed. starting RTL again it crashes within minutes so i'm sure it's being caused by RTL somehow.

**Comment by ShahanaFarooqui** [comment]
@sendbitcoin Thank you for raising the issue.

- Did it start happening after any particular RTL version upgrade? For example, it happened initially with v11/v12 upgrade?

- Does this lnd node has a large amount of payments & invoices? Some of our users are complaining about RTL taking minutes for initial load and the issue is already on top priority. However, I am not sure if the system can crash just because of it. 

This is the first complain about system crash and we might need more information before being able to fix it.

**Comment by sendbitcoin** [comment]
I dont remember exactly with which version I first noticed the issue but it was after a major update, i think after going to version 11. i have since upgraded again hoping to fix the problem but it still persist. currently i just don't run RTL at all as it's become a huge hassle.

If you need further information and logs i'd be happy to assist

**Comment by sendbitcoin** [comment]
>Does this lnd node has a large amount of payments & invoices? 

yes (just starting rtl for a moment trying to get the screenshot made the pc crash twice)

i think there is over 220'000 invoices, but pc chrashed before i could screenshot

**Comment by ShahanaFarooqui** [comment]
@sendbitcoin Thanks for the information and apologies for the inconvenience.

Most probably, this is happening because of the large amount of transactions. Other nodes with large data volume are also experiencing delayed application load, but none of them have complained about the crash. However, v0.12.3 should have improved the situation a little as we moved the request to get all invoices from RTL's initial load to reports menu. 

Another option to check is that the `logLevel` in RTL-Config.json is set to `ERROR`. The lower level of logging will slow the application. 

We have also opened some issues with LND to fix these issues:
- https://github.com/lightningnetwork/lnd/issues/6459
This will allow us to move the request to get all payments, also from RTL's initial load to reports menu. We should be able to implement it as soon as LND's next release.

- https://github.com/lightningnetwork/lnd/issues/6532
- https://github.com/lightningnetwork/lnd/issues/6533
These issues will enable us to filter the records for reports menu as well. So that reports page will also not take time/crash.

Can you please also share your system configuration?

**Comment by sendbitcoin** [comment]
![image](https://user-images.githubusercontent.com/60074674/168493125-b997d290-2c76-4051-9d64-e04fa8445483.png)

![image](https://user-images.githubusercontent.com/60074674/168493052-af9ff030-1676-4f66-92c9-b51f78a64c24.png)

![image](https://user-images.githubusercontent.com/60074674/168493141-2e0d3b3e-81ce-45e7-ba33-ab8d845e5f38.png)

![image](https://user-images.githubusercontent.com/60074674/168493076-5cac924e-2c97-4a1e-bfc6-820b34cae853.png)

![image](https://user-images.githubusercontent.com/60074674/168493089-9a7af67f-418b-464c-a839-01fc61ee72e0.png)

![image](https://user-images.githubusercontent.com/60074674/168493279-ae9aa4ee-8b62-4853-8a3d-8c5be37440db.png)

RTL 12.3

log level is already on error

is it possible to purge old data in lnd somehow?

**Comment by sendbitcoin** [comment]
fixed system instability by removing overclocking and updating bios, closing issue
