### ISSUE TITLE
Add "Send all funds" feature

### ISSUE THREAD

**Issue by samo-sato** [Ride-The-Lightning/RTL#1473]
**Issue description**
Unable to send whole on-chain balance

**Description of solution of feature request**
Add feature "Send all funds" to send whole balance and automatically subtract miner fee from that

![Screenshot at 2024-11-20 12-58-17](https://github.com/user-attachments/assets/4cb074d5-0b7e-4410-a5e2-fa1eab0f9286)

**Comment by ShahanaFarooqui** [comment]
It is already available for CLN and LND nodes and can be found on the "Sweep All" tab on your page. Since this feature requires users to re-authenticate, we implemented it as a separate page rather than a checkbox in the above model.

![Screenshot from 2024-11-20 12-03-47](https://github.com/user-attachments/assets/b2f084fb-800e-40f6-95c6-914e31d0f8a4)
