### ISSUE TITLE
RTL.conf macaroon path is not being found

### ISSUE THREAD

**Issue by TyBranham** [Ride-The-Lightning/RTL#205]
I am running bitcoind and lnd, lnd is synced with the btc mainnet. After I start LND, I can input my unlock wallet password in RTL and I see in the CLI that it does indeed unlock and is communicating with the network but I also receive this error logged.

ERROR: Wallet(83) => Wallet Response: {"error":"transport is closing","code":14}

The node continues to initialize in RTL but eventually stops and remains on the wallet unlock screen. The below error is then logged. Obviously this is indicating that my macaroon path is incorrect, but the path in the error is the correct path. I doubt this is a true bug, I am more looking for support in things I could have missed. Thank you.

Common Set Options Error:{"errno":-2,"code":"ENOENT","syscall":"open","path":"[redacted]/.lnd/data/chain/bitcoin/mainnet/admin.macaroon"}
Common Update Selected Node Options Error:{"errno":-2,"code":"ENOENT","syscall":"open","path":"[redacted]/.lnd/data/chain/bitcoin/mainnet/admin.macaroon"}
Console: 
INFO: GetInfo => Single Node Setup!
Console: 
ERROR: GetInfo(17) => Get info failed due to bad or missing macaroon!

**Comment by ShahanaFarooqui** [comment]
@TyBranham the 'transport is closing' error is expected and can be ignored while unlocking the wallet. according to your log, you are able to unlock the wallet but unable to get data from the lnd node due to missing macaroon. 

Error `"errno":-2,"code":"ENOENT","syscall":"open"` is definitely related to missing admin.macaroon file in the above path or the path seems to be incorrect/misspelled. Can you please try below:

Copy `admin.macaroon` file from above path.
Paste the file at some other folder (root/some shorter path)
Update your RTL.conf's macaroon path to the newer path and restart RTL.

**Comment by TyBranham** [comment]
Hi, I moved this to a different folder and it did work. I think however I was not properly stopping rtl. I will attempt to change the macaroon path back and see if it still works. If not, is it ok just to leave in a different folder?

**Comment by ShahanaFarooqui** [comment]
@TyBranham Thank you for your kind words :).

It is perfectly fine to keep the macaroon file in a different folder. In some cases like, accessing the node remotely, it is the suggested solution. But, if you are using the application on the same machine, we would recommend to keep a single copy of the macaroon at it's original folder. So, recheck the path and set the macaroonPath back to original first. If that doesn't work after restarting the RTL then keep it in both folders.

**Comment by saubyk** [comment]
Hi @TyBranham assuming this issue has been addressed now. Closing this ticket.
Feel free to re-open if the issue re-appears or you need help. Thanks.
