### ISSUE TITLE
Searching for a node you are already connected to removes it from the list of peers

### ISSUE THREAD

**Issue by bolatovumar** [Ride-The-Lightning/RTL#215]
**Describe the bug**
As the title says, searching for a node you are already connected to removes it from the list of peers below the search field.

**To Reproduce**
1. Go to 'Peers' tab
2. Search for a peer you are already connected to
3. You will get an error that you are already connected to it (screenshot below)
![Screen Shot 2019-12-28 at 6 36 07 PM](https://user-images.githubusercontent.com/1934678/71551674-ad2b7000-29a1-11ea-9064-6c55f90299b3.png)
4. See that the node you searched for disappears from the list of peers below

**Expected behavior**
A node you searched for does not disappear from the list of peers if you are already connected to it.

**Actual behavior**
A node you searched for does disappears from the list of peers if you are already connected to it.

**Your environment**
* RTL v0.5.1

**Comment by ShahanaFarooqui** [comment]
@bolatovumar It was a bug in the code and has been fixed in master. But, we decided to release it in the near future with the new UX. To fix the error at your end, do consider the below options:

Pull the code from master
OR
Pull the code from UX branch (we are inviting alpha testers for the new UX anyway)
OR
Continue with the current version till the next release as it is not a critical bug.

**Comment by bolatovumar** [comment]
@ShahanaFarooqui it's not a big deal for me, just thought I would bring it up if it hasn't been brought up already. I'm closing this issue if this has been fixed already.
