### ISSUE TITLE
What is the point of index in configuration/can it be removed?

### ISSUE THREAD

**Issue by Kixunil** [Ride-The-Lightning/RTL#282]
I don't understand why index is in the config file. It should be possible to calculate it automatically from the position in the array, but maybe I'm missing something? I'm trying to figure out what would be a good automated way to add/remove nodes and I don't know how to assign indexes properly.

**Comment by ShahanaFarooqui** [comment]
Multinode configuration logic depends heavily on node’s index. Though it can be calculated automatically, it is better to add one property in the file rather than calculating and filtering the node multiple times. So, it will not be possible to remove it from config.

The index is starting from 1 and can be increased by one for the new node.

We are already working on the UX to be able to add new node through the UI. But that will take some more time to implement.

**Comment by Kixunil** [comment]
Couldn't they be calculated at the beginning of the program and inserted to the object? Since I'm generating the configuration automatically, would it be a problem if the indexes reorder sometimes? Example:

* the user starts with one node, index 1
* later the user adds another node, but this one gets index 1 assigned for some reason and the previous one gets index 2

Could this cause any problem other than default node changing?

**Comment by ShahanaFarooqui** [comment]
Calculating them at the runtime can cause confusion and not possible at this point.

Indices reordering at runtime is NOT recommended, as channel backup, data reading, data writing (basically all the operations), are dependent on node index. Updating it can result in data corruption and loosing money.

Indices can be sparse as long as they are unique.

RTL already supports some settings to update at /settings/layout page. Can you share the list of properties which you might want to opt out from? Below are the current screen desgins which will be released in the next version.

https://github.com/Ride-The-Lightning/RTL-Design/pull/43/files?short_path=893a48f#diff-893a48fc10ca464098f21d1523e3b2de

https://github.com/Ride-The-Lightning/RTL-Design/pull/44/files

**Comment by Kixunil** [comment]
OK, I'll try to figure out some sort of index allocator. Not sure how it'll work, but would it be possible to allow string indices too? Might allow for an easier algorithm like `username-uuid`.

Basically, my thinking is to hide all arcane strings from the UI, like IP addresses, ports, macaroons certificates. Setting visual things like color scheme or persona in UI is good.

What I want to have is a separate tool that enables the user to add/remove wallets using a more user-friendly way and connect it to multiple other services automatically (e.g. RTL, BTCPayServer, mobile wallets, monitoring tools...) I'm building the base infrastructure for this now.

**Comment by Kixunil** [comment]
What exactly does "Indices reordering at runtime is NOT recommended" mean? Can I shutdown RTL, change the indices and relaunch it? Because that was my original intention anyway and it'd solve my problem very well.

If not, would it be possible to have a simple tool to change the indices (presumably in the database) explicitly? I'm imagining something like `nodejs rtl-change-index.js 1 2` to change node index from `1` to `2`. This combined with string indices would be quite powerful: I'd assign a random UUID before wallet initialization and then change it to the node ID, which will always be unique and fixed for given node. But if direct support for this was implemented, it'd be even nicer, as I wouldn't have to monitor initialization of the node.

**Comment by ShahanaFarooqui** [comment]
Please check my comments below:

- OK, I'll try to figure out some sort of index allocator. Not sure how it'll work, but would it be possible to allow string indices too? Might allow for an easier algorithm like username-uuid
* String indices are not allowed. 

- Basically, my thinking is to hide all arcane strings from the UI, like IP addresses, ports, macaroons certificates. Setting visual things like color scheme or persona in UI is good.
* We can add "disableNewNodeSetup" variable in the config to address this requirement.

- What exactly does "Indices reordering at runtime is NOT recommended" mean? Can I shutdown RTL, change the indices and relaunch it? Because that was my original intention anyway and it'd solve my problem very well.
* Stoping and restarting the server after editing index value will not corrupt the data received from API. But, server restart initiates some operations like cleaning the logs, backing up the channels, etc. Editing indices and restarting the server, can cause confusion and end up in data corruption. So again, I would highly suggest to NOT to edit the index once it is assigned to a node. 

- If not, would it be possible to have a simple tool to change the indices (presumably in the database) explicitly? I'm imagining something like nodejs rtl-change-index.js 1 2 to change node index from 1 to 2. This combined with string indices would be quite powerful: I'd assign a random UUID before wallet initialization and then change it to the node ID, which will always be unique and fixed for given node. But if direct support for this was implemented, it'd be even nicer, as I wouldn't have to monitor initialization of the node.
* RTL architecture has not been designed to update/edit the node indices once they are assigned. It will be a huge effort to enable index editing and we are not considering the option currently.

**Comment by Kixunil** [comment]
Thanks for a detailed answer! I'll try to avoid changing indices (avoiding it in the MVP of my project is trivial anyway). In some extreme scenarios I might be motivated enough for a PR. :)

I'd suggest to document these important properties of indices:

* They should not be changed
* They can be sparse
* The allowed range of indices (lower bound is 1, what's the upper bound?)

**Comment by Kixunil** [comment]
So I've created a pretty [robust index allocator](https://github.com/Kixunil/cryptoanarchy-deb-repo-builder/blob/master/ridetheln/alloc_index.sh), which seems to work well. Thus I consider this issue resolved.

However, maybe it'd be useful for you to include the allocator for others? If yes, feel free, just please let me know to update my build scripts. :)
