### ISSUE TITLE
Verification failed while extracting material-design-icons@3.0.1

### ISSUE THREAD

**Issue by marssystems** [Ride-The-Lightning/RTL#344]
**Describe the bug**
admin@raspberrypi:~ $ git clone https://github.com/Ride-The-Lightning/RTL.git

admin@raspberrypi:~/RTL $ npm install --only=prod
npm WARN tarball tarball data for material-design-icons@3.0.1 (sha1-mnHEh0chjrylHlGmbaaCA4zct78=) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for material-design-icons@3.0.1 (sha1-mnHEh0chjrylHlGmbaaCA4zct78=) seems to be corrupted. Trying one more time.
npm ERR! code EINTEGRITY
npm ERR! Verification failed while extracting material-design-icons@3.0.1:
npm ERR! Verification failed while extracting material-design-icons@3.0.1:
npm ERR! sha1-mnHEh0chjrylHlGmbaaCA4zct78= integrity checksum failed when using sha1: wanted sha1-mnHEh0chjrylHlGmbaaCA4zct78= but got sha512-IpKXO/KSIvNLMF/zYCbEIaRJjVwh//x1sK0BamrEZSbMyDpaKbkDftxPgJ8hNjejTJk1ep0g49g7pnv5ZXVQ8A== sha1-ePZRESZodkIlKozunP/Z7b2afuE=. (14686610 bytes)

**To Reproduce**
Follow instructions to install RTL version 7.0.1
**Screenshots**

**Your environment**
* Version of `RTL` 0.7.0
* Version of `lnd` 0.10.0-beta
* Version of `btcd`, `bitcoind`, or other backend 0.19.1
* Browser & browser version Microsoft Edge
* Operating system (`uname -a` on *Nix) Rasbian Buster
* any other relevant environment details

**Additional context**

**Comment by ShahanaFarooqui** [comment]
@marssystems This issue is not related to RTL, instead npm is unable to install the package on your machine for some reason. Please try following steps:

1: Delete node_modules
2: Delete package-lock.json
3: Run 'npm cache verify'
4: Run 'npm install --only=prod'

Hopefully, it should resolve the issue and all the dependencies should be installed successfully. If not, below are some references to resolve npm tarball issues:

https://github.com/google/material-design-icons/issues/853
https://stackoverflow.com/questions/52739973/npm-tarball-data-for-material-design-icons-seems-to-be-corrupted
https://stackoverflow.com/questions/53146612/npm-error-eperm-operation-not-permitted-tarball-data-for-package-seems-to-b
https://npm.community/t/getting-issue-in-npm-install-warn-tarball-tarball-data-for-angular-compiler-7-1-0/3887/8

**Comment by marssystems** [comment]
No - whatever I try, I can't update RaspiBlitz 1.5 to v0.7.1 of RTL.
I used the RaspiBlitz menu system to remove RTL and then re-install it.
The install went without a hitch.
I expected the install to pick up the latest version of RTL from source but it installed v.0.7.0 again.
I don't know if this is a RaspiBlitz or an RTL problem but everything I have tried so far hasn't worked on RaspiBlitz 1.5. I had no problems upgrading on RaspiBlitz 1.4.

**Comment by saubyk** [comment]
@marssystems  Sounds like a RaspiBlitz issue. Have you consulted with @openoms or @rootzoll?

**Comment by openoms** [comment]
Did not test the RTL 0.7.1 yet, but the errors seem like to.be releated to data corruption.
Would recommend trying with a new SDcard. (get an endurance one).

**Comment by marssystems** [comment]
The SD card is a brand new Samsung Evo Plus 16Gb with a fresh install of RaspiBlitz 1.5. The upgrade from 1.4 to 1.5 went perfectly, with no issues. The re- installation of RTL from the RaspiBlitz menu went perfectly, so it can't be an SD card issue.
When I follow these instructions - 
Installation
First time setup
Fetch sources from RTL git repository, by executing the below on the command prompt:
$ git clone https://github.com/Ride-The-Lightning/RTL.git

Change directory to RTL folder:
$ cd RTL

Fetch the production dependencies by running: $ npm install --only=prod

that's when the problems start.

I will raise the issue with RaspiBlitz and see what they think about it.

**Comment by marssystems** [comment]
Tried again last night. Everything installed without issue but didn't update to ver. 0.7.1. Still at ver.0.7.0
Closing this issue.
