### ISSUE TITLE
Closing channel shows error sometimes even though it works fine

### ISSUE THREAD

**Issue by sendbitcoin** [Ride-The-Lightning/RTL#496]
When you close a channel RTL sometimes gets stuck on "closing channel..." for like 10 minutes. after the timeout it shows this error:

![2020-09-26 22_40_55-192 168 1 195 - Remotedesktopverbindung](https://user-images.githubusercontent.com/60074674/94349903-6b6f4900-0049-11eb-8f81-0101f0bc464e.png)

In lnd I can see that the channel was closed just fine though and if I reload RTL the channel dissapears as it was cooperatively closed successfully

judging by the logs it looks like some kind of timing problem. perhaps LND has already closed the channel but RTL still thinks it has to close it but can't find the channel link anymore so it waits for timeout?

![2020-09-26 21_07_14-192 168 1 195 - Remotedesktopverbindung](https://user-images.githubusercontent.com/60074674/94349928-8e016200-0049-11eb-8fb1-6302718db5d0.png)

**Comment by saubyk** [comment]
Hi @sendbitcoin RTL waits for the API response and times out after 10 mins. This is a compromise we've made for the usability of the application. If we don't do this, the application will be locked out until you get a response back from LND, which is not an ideal experience.

So, in some cases, where it may take more than 10 mins to even cooperatively close the channels, RTL would timeout and throw an error on the page, but the close channel command can still get executed, without the channels going into a pending closing state.

Although looking at the specific scenario that you have pasted above, LND throws an error in the log, but does not return the same in the API response (since RTL would wait for at least 10 mins before timing out). This is weird and is best addressed by LND, not RTL.

Hope this is clear. Closing this issue, as we do not feel we have any specific action path here.
