### ISSUE TITLE
Ability to change date-format based on user locale

### ISSUE THREAD

**Issue by dipunm** [Ride-The-Lightning/RTL#537]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I can't work out what a date/time value means. In the US, it is Month/Day/Year, in the UK, it is Day/Month/Year. The one that is the most consistent is called sortable date-time format Year/Month/Day (eg. 2020/11/10).

**Describe the solution you'd like**
A simple solution is to use sortable date formats, but if using a date/time library like moment, then you can set a global language/locale and allow it to format dates as well as numbers (some cultures use commas in place of periods).

**Describe alternatives you've considered**
Another solution would be to use a clearer format like 10-Nov-2020 or Nov-10-2020 (<- is that a standard format?)

**Additional context**
The place where I noticed this was on the routing page. There is a filter set and it showed: 
Start Date: 10/11/2020 End Date: 11/10/2020

**Comment by sendbitcoin** [comment]
I'd like to add that the time displayed by RTL is always off by one hour for me (i guess because of daylight saving time or timezone issue) -> currently RTL is not using the same timezone/time as the computer -> please add ability to set timezone or just refer to the internal clock for getting time

it's a minor issue but it's still kinda annoying when the times are always off by 1 hour

**Comment by ShahanaFarooqui** [comment]
@dipunm Thanks for the issue. We have configured the date picker with our default date format, ie 'DD/MMM/YYYY' (10/NOV/2020).

@sendbitcoin, For now, we are not considoring to add ability to set the timezone. However, we are now refering to the local time. Hopefully, it will fix your issue :).
