### ISSUE TITLE
Is there a way to create "proper" optimized release build?

### ISSUE THREAD

**Issue by Kixunil** [Ride-The-Lightning/RTL#581]
RTL takes up 760MB on my machine. For comparison, `electrs` takes 4.4MB, `bitcoind` takes 9.9MB.
This seems suspiciously high, so I wonder if I'm doing it properly. Perhaps I should supply some switch to optimize it?

I'm using `npm install --build-from-source` to build it and then copy the whole directory without some obvious things like dockerfiles, readme....

**Comment by ShahanaFarooqui** [comment]
@Kixunil Thanks for the issue.

1: Usually, SPA projects are heavier than non-SPA due to heavier libraries dependency.

2: RTL already has prebuild angular frontend and do not require any other build process. I am confused about the benefit of using `--build-from-source` flag above.

3: Size of the project can be controlled by installing dependencies which are required for production environment only. This can be achieved by executing the command as `npm install --prod`. 

4: The size can further be reduced by copying/downloading only mandatory folders & files. Users can include/exclude others as per their project requirements. Currently, the minimum size of the project is 303MB (below folders & files) and maximum size is 496MB (the whole project folder), including production dependencies.

Mandatory items list:
- Folders:
    - angular
    - controllers
    - routes
 - Files:
     - app.js
     - common.js
     - connect.js
     - rtl.js
     - package.json
     - package-lock.json

**Comment by Kixunil** [comment]
> I am confused about the benefit of using --build-from-source flag above.

* Guarantees that there's not a *covertly* backdoored native library
* It's required for cross compiling if I remember correctly

> This can be achieved by executing the command as `npm install --prod`.

Ah, forgot to mention that I run `npm prune --production` afterwards, which to my knowledge should have the same effect.

I will try to check if I have unneeded files in the release, thanks for the list!

**Comment by ShahanaFarooqui** [comment]
AFAIK, `--build-from-source` is not a valid argument for npm install or config. 
- [Command npm install](https://docs.npmjs.com/cli/v6/commands/npm-install)
- [Configuring npm](https://docs.npmjs.com/cli/v6/using-npm/config)

So, we can assume that:
- Initially `npm install --build-from-source` command installs all dependencies (including dev) while ignoring invalid argument and executing the command as `npm install`.
- Once that is done, `npm prune --production`  command removes development dependencies. 

The faster and easier way to achieve the same, is to run a single command as `npm insall --prod`.

**Comment by Kixunil** [comment]
Yes, what you described applies to RTL today. `--build-from-source` is used by `gyp`, which RTL doesn't use now. I use same commands to build multiple projects and doing what I described is needed in those other projects. Perhaps not an awesome approach but I don't think it's too bad either. At worst it causes RTL build to take longer.

**Comment by ShahanaFarooqui** [comment]
Closing the issue as nothing else is required for this.
