### ISSUE TITLE
Option to use full balance from onchain to open channel

### ISSUE THREAD

**Issue by Darth-Coin** [Ride-The-Lightning/RTL#618]
**Is your feature request related to a problem? Please describe.**
Yes, if I want to open a channel with all the balance available, I never could calculate the exact fee and size of the channel to be empty the UTXO from the onchain wallet. Opening several channels will end up in having many UTXOs with dust, that will increase in time the cost of new txs.

**Describe the solution you'd like**
A simple tick box that can say: "click here if you want to use all balance available, minus de fee"

**Comment by saubyk** [comment]
Hi @Darth-Coin which lightning implementation are you using?

**Comment by Darth-Coin** [comment]
> Hi @Darth-Coin which lightning implementation are you using?

LND from Umbrel node, latest version

**Comment by saubyk** [comment]
Hi, this feature is best handled at the lightning implementation level i.e. LND should handle this and provide an option (flag) via the channel open API to utilize the full amount in the UTXO. Since LND is doing the fee estimation and transaction crafting as well.

E.g. in C-Lightning you have the option to pass `all` to indicate that all the UTXO funds should be utilized to open channel.

Closing this ticket, since LND is actually working on addressing this at the implementation level. Once the API support is available, will enable it in RTL.

Please look at the below issue and PR on LND
https://github.com/lightningnetwork/lnd/issues/619
https://github.com/lightningnetwork/lnd/pull/4029
