### ISSUE TITLE
[Feature Request] Enable CPFP to get stuck channel opening and closing transactions unstuck

### ISSUE THREAD

**Issue by viaj3ro** [Ride-The-Lightning/RTL#633]
By now I have more than 0.5  BTC stuck in limbo indefinitely due to bitcoin-qt and eclair missing CPFP functionality and me being unwilling to mess around with manually created raw transactions that could easily make matters worse.

I opened an issue in bitcoin-core, but so far it doesn't seem like much is happening there: https://github.com/bitcoin-core/gui/issues/242

Could this be implemented in RTL as well?

**Comment by saubyk** [comment]
Hi @viaj3ro the CPFP feature in RTL is dependent on the underlying lightning implementation.
We've enabled it in LND, because LND provides an API to bump up the transaction fee. Also, do note that CPFP would require signing the transaction with the private key of the wallet, which RTL does not have access to.

Can we raise it with Eclair, so that they can address it via an API? Once we have the API support, enabling it in the UI is easy.

**Comment by viaj3ro** [comment]
I raised the issue with eclair a while ago and it's on their to do list. Pressed again for a timely implementation today. Hopefully it won't be too long.

**Comment by saubyk** [comment]
Closing this, as no action can be taken from our end until support is enabled in Eclair
