### ISSUE TITLE
Home/Dashboard button top left menu

### ISSUE THREAD

**Issue by manakill** [Ride-The-Lightning/RTL#637]
I have to bookmark the main dashboard page to get back to it quickly. It should be on the main menu, in my opinion.

/rtl/lnd/home

**Comment by Svobodan** [comment]
In tor browser it happened to me only once that the "dashboard" button became invisible. It glitched and somehow it was hidden underneath the top pannel. Tor Browser 10.0.13; Fedora 33. But normally it's there.
![image](https://user-images.githubusercontent.com/77900472/113405590-600b2a80-93aa-11eb-8bfe-c5f989c02089.png)

**Comment by manakill** [comment]
Weird, it's not showing in my Tor browser, nor Firefox, on either of my machines (win 7 and win 10). So maybe it's more of a bug than a feature request, I guess.

**Comment by manakill** [comment]
Actually it IS there when I first log in! Then it disappears when I navigate to another page, the menu changes to have no Dashboard

**Comment by ShahanaFarooqui** [comment]
@manakill Thanks for opening the issue. It looks like a related issue to #268, #417, #464 & #619. 

Assuming that you are using RTL for a single node setup and you are changing page size of some table. The other users from those issues were using multinode setup and their node selection dropdown (which shows on top of the dashboard menu) was getting disappeared. 

The issue has been fixed with PR #645 and will be released with v0.10.2. You can either test the fix from the current [release](https://github.com/Ride-The-Lightning/RTL/tree/Release-0.10.2) branch or wait till the next release. Please let us know if the issue persists after update.

**Comment by ShahanaFarooqui** [comment]
Closing the issue with Release v0.10.2
