### ISSUE TITLE
Paying zero amount invoice fails with incorrect_payment_details

### ISSUE THREAD

**Issue by mmilata** [Ride-The-Lightning/RTL#657]
**Describe the bug**
Payments to tippin.me (which generates 0sat invoices) fail with `incorrect_payment_details`.

**To Reproduce**
1. Go to tippin.me user of your choice, e.g. https://tippin.me/@nobsbitcoin and copy the invoice.
2. Paste invoice to RTL's *Send Payment* dialog. Set amount to e.g. 1.
3. Set fee limit.
4. See error `incorrect_payment_details`.

**Screenshots**
![Screenshot_2021-04-16 RTL](https://user-images.githubusercontent.com/85857/115042679-03445f80-9ed4-11eb-96e5-f32953875613.png)

**Your environment**
* Version of `RTL`: 0.10.1-beta
* Version of `lnd`: 0.12.1-beta
* Version of `bitcoind`: 0.21.0
* Browser & browser version: Firefox 87
* Operating system (`uname -a` on *Nix): Linux
* any other relevant environment details: The LND node has direct channel to tippin.me.

**Additional context**
The payment succeeds when the same invoice is given to `lncli payinvoice --amt 1234 <invoice>`.

**Comment by ShahanaFarooqui** [comment]
@mmilata Thanks for opening the issue and the details.

After discussion with LND team and on their suggestion, we have updated the JSON body for the send payment POST. Previously, we were passing `dest_string` and `amt` details for the empty string. After the fix, we will pass `payment_request` and `amt` details for the same. 

The issue has been fixed with PR #658. It can be tested from the [release](https://github.com/Ride-The-Lightning/RTL/tree/Release-0.10.2) branch and will be released with v0.10.2.
