### ISSUE TITLE
Update Fee Rate Cards

### ISSUE THREAD

**Issue by ShahanaFarooqui** [Ride-The-Lightning/RTL#761]
Response signature of fee rates has been modified and the UI needs to be remapped accordingly.

Perkb Response:
{
  "perkb": {
    "opening": 1012,
    "mutual_close": 1012,
    "unilateral_close": 1012,
    "delayed_to_us": 1012,
    "htlc_resolution": 1012,
    "penalty": 1012,
    "min_acceptable": 1012,
    "max_acceptable": 4294967295
  },
  "onchain_fee_estimates": {
    "opening_channel_satoshis": 177,
    "mutual_close_satoshis": 170,
    "unilateral_close_satoshis": 151,
    "htlc_timeout_satoshis": 167,
    "htlc_success_satoshis": 177
  }
}

Perkw Response:
{
  "perkw": {
    "opening": 253,
    "mutual_close": 253,
    "unilateral_close": 253,
    "delayed_to_us": 253,
    "htlc_resolution": 253,
    "penalty": 253,
    "min_acceptable": 253,
    "max_acceptable": 4294967295
  },
  "onchain_fee_estimates": {
    "opening_channel_satoshis": 177,
    "mutual_close_satoshis": 170,
    "unilateral_close_satoshis": 151,
    "htlc_timeout_satoshis": 167,
    "htlc_success_satoshis": 177
  }
}

**Comment by saubyk** [comment]
We should display all the information we are getting in the updated response from C-Lightning.

In addition, we should also add definitions for these data items, so that user can understand the information better. Below are the definitions which can be added on mouse over:
- min_acceptable - The smallest feerate that you can use, usually the minimum relayed feerate of the backend
- max_acceptable - The largest feerate we will accept from remote negotiations.  If a peer attempts to set the feerate higher than this we will unilaterally close the channel (or simply forget it if it's not open yet)
