### ISSUE TITLE
Display channel uptime/downtime in the UI

### ISSUE THREAD

**Issue by pavlenex** [Ride-The-Lightning/RTL#82]
**Is your feature request related to a problem? Please describe.**
I would really like to be able to see the channels uptime/downtime if that's possible. It would tremendously help me quickly discover channels that don't have the uptime I want.

**Describe the solution you'd like**
Show down/up time in channel management somehow (if possible) or just some sort of indicator `hey this node is bad, it's down most of the time and therefore useless`

**Comment by saubyk** [comment]
@pavlenex 
Getting a uptime/downtime is a bit of a challenge at this point, because we are not maintaining a local database at RTL, to track this type of metric.

What we can do is, figure the channel age, by decoding the channel ID and determine the block on which the channel is included. This can give you better information about your channel.

**Comment by saubyk** [comment]
Channel ID decoding reference:
https://github.com/alexbosworth/bolt07/blob/master/lib/components_from_buffer.js

**Comment by ShahanaFarooqui** [comment]
@saubyk, Need more details on how to address it.

**Comment by ShahanaFarooqui** [comment]
@pavlenex, Thanks for the sugeestion.

After discussing the issue with Suheb, we added LND's channel response "uptime" on the open channels table. "lifetime" and other newly added fields can be checked with "view info" option. We are unable to calculate "downtime" for now and will wait till LND provides it.

Pushed the code in 0.6.5 branch and will be releases soon.
