### ISSUE TITLE
Profit & Loss report tab

### ISSUE THREAD

**Issue by hieblmi** [Ride-The-Lightning/RTL#921]
As a routing node operator it is cumbersome to determine the profit/loss from the existing tabs "Routing Fees" and "Transactions" since one has to look at the routing fees for a day and subtract the difference between paid/received from transactions.

**Describe the solution you'd like**
Add an additional tab that shows profit and loss per day, per months...(with a hint that non routing activity is not considered, e.g. real payments)
![image](https://user-images.githubusercontent.com/18631614/148412831-0750618e-1f73-43a3-922c-946378361d6c.png)

**Describe alternatives you've considered**
Manually calculating ' routing fees - ( transactions paid - transactions received )'

**Comment by saubyk** [comment]
Hi @hieblmi there are couple of problems here, because of which we are not making progress on this issue.

1. The data in the reports tab is not a complete picture of your expenses and income. Expenses on the node also include the fee spent in opening/closing channels as well. So, it's not fair to calculate Profit/Loss just from routing fee and transaction activity.
2. Ideally accounting functions should be part of the node's backend. It's not a good idea for applications to be estimating that. Otherwise, it creates separate sources of truth. Both LND and C-Lightning have some node accounting projects, which should provide us the accounting insight we need. So we would rather wait for that.

Closing this issue for now. Thanks.

**Comment by hieblmi** [comment]
Thank you @saubyk, i wasn't aware of the accounting functionality efforts of LND/cL.

I am aware of the complications with channel opening/closing fees but for medium size node operators these can sometimes be approximated or omitted especially when the node is not growing it's capacity and taking in a fair bit of fees.

Thanks again!
