### ISSUE TITLE
.cookie file is not generated in docker container from version 0.12.0 onwards

### ISSUE THREAD

**Issue by zoop-btc** [Ride-The-Lightning/RTL#990]
**Describe the bug**
The .cookie file for SSO logon is not being generated when using the dockerhub container.
This happened to me in a freshly deployed btcpayserver deployment. I had to launch it with version 0.11.2 so the cookie gets generated first.

**To Reproduce**
1. Launch the docker container with the environment variables RTL_SSO=1 and RTL_COOKIE_PATH=/data/.cookie where /data/ is a mounted docker volume
2. docker exec into it and see that no file was created

**Screenshots**
![image](https://user-images.githubusercontent.com/101409458/162616517-a7b24e4c-09d0-4d99-8934-c7d078cfceb8.png)

**Your environment**
* Version of `RTL` - 0.12.0/0.12.1/0.12.2
* Version of `lnd` - NA
* Version of `btcd`, `bitcoind`, or other backend - NA
* Browser & browser version - NA
* Operating system (`uname -a` on *Nix) - Linux btcpaytest 5.10.0-12-amd64 #1 SMP Debian 5.10.103-1 (2022-03-07) x86_64 GNU/Linux
* any other relevant environment details - I have followed the [official btcpay docker instructions](https://docs.btcpayserver.org/Docker/)

**Additional context**
none

**Comment by NicolasDorier** [comment]
Note that I recently updated RTL https://github.com/btcpayserver/btcpayserver-docker/commit/58b87536604478a5682f2446b1dd19a1741c1a09

Should we go back to `0.11.2` ? what happen to people who already migrated?

**Comment by ShahanaFarooqui** [comment]
@zoop-btc Thank you for raising the issue. This bug was introduced due to the RTL server's recent migration from javascript to typescript. It has been fixed with PR #994.

@NicolasDorier We will soon release the fix with version 0.12.3. 
- Users who migrated to 0.12.x versions from any older versions should not be affected by this bug as they already must have the cookie file in their mounted volume. 
- New users with v0.12.x can create the cookie file manually as a temporary solution.
