### ISSUE TITLE
on Palemoon 30.0.1 the open channel window isn't fully visible

### ISSUE THREAD

**Issue by maximlomans** [Ride-The-Lightning/RTL#992]
**Screenshots**

![rtl-ScreenCapture](https://user-images.githubusercontent.com/6319093/163023703-1cc3704e-d3fe-4d44-adc8-e866dd43ac15.PNG)

Size of the window - advanced options not visible nor available, neither in fullscreen mode. 

**Your environment**
 Raspiblitz 1.7.1

* Version of `RTL`
 0.11.0.2-beta

* Version of `lnd`
 0.13.3-beta

* Version of `btcd`, `bitcoind`, or other backend
v22.0

* Browser & browser version
Palemoon 30.0.1

* Operating system (`uname -a` on *Nix)
win 7
* any other relevant environment details

**Additional context**

**Comment by ShahanaFarooqui** [comment]
@maximlomans Thanks for raising the issue. The extension panel is visible now. 

However, Palemoon's team might need to add/fix few default flex layout settings at their end. As you can see in the below image that, the modal adds more space between elements while decreasing the accordion header height. Otherwise, these missing/incorrect default settings might raise more UI issues in the future.

![image](https://user-images.githubusercontent.com/23240721/163442564-aad2ea98-a9a6-45e5-9087-1aa01d3c9ffe.png)

Closing the issue with PR #993.

**Comment by maximlomans** [comment]
Thanks - I have been using Brave in the meantime - i'll check Palemoon and file bug report on its forum
